
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })
import Header from './components/Header';
import Footer from './components/Footer';
import HomeFooter from './components/HomeFooter'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    
    <html lang="en">
      
    <head />
    
        <body>
         
          <Header />

          

          <main >{children}</main>

         
          {/* {isHomePage ? <HomeFooter /> : <Footer />} */}
        </body>

  </html>
    
  )
}
